---
image_resource:
  source:
    repository: "dpb587/bosh-release-blobs-upgrader-pipeline"
  type: "docker-image"
inputs:
- name: "repo"
- name: "blob"
outputs:
- name: "repo"
  path: "updated-repo"
params:
  blob: ~
  track_files: ~
platform: "linux"
run:
  path: "/opt/bosh-release-blobs-upgrader-pipeline/bin/sync-blobs"
